<template>
  <v-container
    class="fill-height"
    fluid
  >
    <v-row
      align="center"
      justify="center"
    >
      <v-col>
        <v-img
          height="90vh"
          src="@/assets/helios_logo.jpg"
        />
      </v-col>
    </v-row>
  </v-container>
</template>
