openapi: 3.0.2
info:
  title: Facturen
  description: Facturen
  version: '1.0'

paths:
  /Facturen/CreateTable:
    post:
      security:
        - basicAuth: []
        - bearerAuth: []
      summary: Creeer database objecten
      parameters:
        - in: query
          name: FILLDATA
          description: Dummy records aanmaken
          required: true
          schema:
            type: boolean
      responses:
        201:
          description: "Aangemaakt, Tabel toegevoegd"
        500:
          description: "Data verwerkingsfout, bijv omdat de tabel al bestaat"

  /Facturen/CreateViews:
    post:
      security:
        - basicAuth: []
        - bearerAuth: []
      summary: Creeer database views
      responses:
        201:
          description: "Aangemaakt, View toegevoegd"
        500:
          description: "Data verwerkingsfout, view niet aangemaak"

  /Facturen/GetObject:
    get:
      security:
        - basicAuth: []
        - bearerAuth: []
      summary: Haal een enkel record op uit de database
      parameters:
        - in: query
          name: ID
          description: Database ID van het track record
          required: true
          schema:
            type: integer
            format: int32
      responses:
        200:
          description: "OK, data succesvol opgehaald"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/oper_facturen'
        404:
          description: "Data niet gevonden"
        405:
          description: "Methode niet toegestaan, input validatie error"
        406:
          description: "Niet aanvaardbaar, input ontbreekt"
        500:
          description: "Data verwerkingsfout, bijv onjuiste veldwaarde (string ipv integer)"

  /Facturen/GetObjects:
    get:
      security:
        - basicAuth: []
        - bearerAuth: []
      summary: Haal een lijst met records op uit de database. Query parameters worden in AND conditie gebruikt
      parameters:
        - in: query
          name: ID
          description: Database ID van het aanwezig record
          required: false
          schema:
            type: integer
            format: int32
            example: 82
        - in: query
          name: VERWIJDERD
          description: Toon welke records verwijderd zijn. Default = false
          required: false
          schema:
            type: boolean
        - in: query
          name: LAATSTE_AANPASSING
          description: Laatste aanpassing op basis van records in dataset. Bedoeld om data verbruik te verminderen. Dataset is daarom leeg
          required: false
          schema:
            type: boolean
        - in: query
          name: HASH
          description: HASH van laatste GetObjects aanroep. Indien bij nieuwe aanroep dezelfde data bevat, dan volgt http status code 304. In geval dataset niet hetzelfde is, dan komt de nieuwe dataset terug. Ook bedoeld om dataverbruik te vermindereren. Er wordt alleen data verzonden als het nodig is.
          required: false
          schema:
            type: string
        - in: query
          name: SORT
          description: Sortering van de velden in ORDER BY formaat. Default = CLUBKIST DESC, VOLGORDE, REGISTRATIE
          required: false
          schema:
            type: string
        - in: query
          name: MAX
          description: Maximum aantal records in de dataset. Gebruikt in LIMIT query
          required: false
          schema:
            type: integer
            format: int32
            minimum: 1
        - in: query
          name: START
          description: Eerste record in de dataset. Gebruikt in LIMIT query
          required: false
          schema:
            type: integer
            format: int32
            minimum: 1
        - in: query
          name: VELDEN
          description: Welke velden moet opgenomen worden in de dataset
          required: false
          schema:
            type: string
        - in: query
          name: LID_ID
          description: Haal alle facturen op van een specifiek lid
          required: false
          schema:
            type: string
        - in: query
          name: JAAR
          description: Haal alle facturen op van een bepaald jaar
          required: false
          schema:
            type: string

      responses:
        200:
          description: "OK, data succesvol opgehaald"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/oper_facturen'
        304:
          description: "Data niet gemodificeerd, HASH in aanroep == hash in dataset"
        405:
          description: "Methode niet toegestaan, input validatie error"
        500:
          description: "Data verwerkingsfout, bijv onjuiste veldwaarde (string ipv integer)"

  /Facturen/NogTeFactureren:
    get:
      security:
        - basicAuth: []
        - bearerAuth: []
      summary: Haal een lijst met records op uit de database. Query parameters worden in AND conditie gebruikt
      parameters:
        - in: query
          name: HASH
          description: HASH van laatste GetObjects aanroep. Indien bij nieuwe aanroep dezelfde data bevat, dan volgt http status code 304. In geval dataset niet hetzelfde is, dan komt de nieuwe dataset terug. Ook bedoeld om dataverbruik te vermindereren. Er wordt alleen data verzonden als het nodig is.
          required: false
          schema:
            type: string
        - in: query
          name: JAAR
          description: Haal alle facturen op van een bepaald jaar
          required: false
          schema:
            type: string

      responses:
        200:
          description: "OK, data succesvol opgehaald"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/oper_facturen'
        304:
          description: "Data niet gemodificeerd, HASH in aanroep == hash in dataset"
        405:
          description: "Methode niet toegestaan, input validatie error"
        500:
          description: "Data verwerkingsfout, bijv onjuiste veldwaarde (string ipv integer)"

  /Facturen/DeleteObject:
    delete:
      security:
        - basicAuth: []
        - bearerAuth: []
      summary: Markeer record als verwijderd.
      parameters:
        - in: query
          name: ID
          description: Database ID van het record. Meerdere ID's in CSV formaat
          required: true
          schema:
            type: string
        - in: query
          name: VERIFICATIE
          description: Controleer of record bestaat voordat het verwijderd wordt. Default = true
          required: false
          schema:
            type: boolean
      responses:
        204:
          description: "Factuur verwijderd"
        401:
          description: "Niet geautoriseerd, geen schrijfrechten"
        404:
          description: "Data niet gevonden"
        405:
          description: "Methode niet toegestaan, input validatie error"
        406:
          description: "Niet aanvaardbaar, input ontbreekt"
        500:
          description: "Data verwerkingsfout, bijv onjuiste veldwaarde (string ipv integer)"

  /Facturen/AanmakenFacturen:
    post:
      security:
        - basicAuth: []
        - bearerAuth: []
      summary: Maak facturen aan voor de leden
      requestBody:
        description: track data
        required: true
        content:
            application/json:
                schema:
                  type: object
                  properties:
                      JAAR:
                        description: Jaar van de factuur
                        type: integer
                        format: int32
                        example: 2014
                      LID_ID:
                        type: array
                        items:
                          type: integer
                        description: Lid ID voor de factuur. Verwijzing naar leden tabel
                        example: [10321, 10201, 10380]

      responses:
        201:
          description: "Facturen aangemaakt"
        401:
          description: "Niet geautoriseerd, geen schrijfrechten"
        405:
          description: "Methode niet toegestaan, input validatie error"
        406:
          description: "Niet aanvaardbaar, input ontbreekt"
        500:
          description: "Data verwerkingsfout, bijv onjuiste veldwaarde (string ipv integer)"

    /Facturen/UploadFactuur:
      post:
        security:
          - basicAuth: []
          - bearerAuth: []
        summary: Maak facturen aan voor de leden
        requestBody:
          description: track data
          required: true
          content:
            application/json:
              schema:
                type: object
                properties:
                  ID:
                    type: integer
                    description: Factuur ID
                    example: 87231

        responses:
          201:
            description: "Facturen upload"
          401:
            description: "Niet geautoriseerd, geen schrijfrechten"
          405:
            description: "Methode niet toegestaan, input validatie error"
          406:
            description: "Niet aanvaardbaar, input ontbreekt"
          500:
            description: "Data verwerkingsfout, bijv onjuiste veldwaarde (string ipv integer)"

  /Facturen/SaveObject:
    post:
      security:
        - basicAuth: []
        - bearerAuth: []
      summary: Voeg nieuw track record toe
      requestBody:
        description: track data
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/oper_factuur_in'
      responses:
        200:
          description: "OK, data succesvol toegevoegd"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/oper_facturen'
        401:
          description: "Niet geautoriseerd, geen schrijfrechten"
        405:
          description: "Methode niet toegestaan, input validatie error"
        406:
          description: "Niet aanvaardbaar, input ontbreekt"
        409:
          description: "Conflict, record bestaat al"
        500:
          description: "Data verwerkingsfout, bijv onjuiste veldwaarde (string ipv integer)"
    put:
      security:
        - basicAuth: []
        - bearerAuth: []
      summary: Update bestaand track record
      requestBody:
        description: track data
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/oper_factuur_in'
      responses:
        200:
          description: "OK, data succesvol aangepast"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/oper_facturen'
        401:
          description: "Niet geautoriseerd, geen schrijfrechten"
        404:
          description: "Data niet gevonden"
        405:
          description: "Methode niet toegestaan, input validatie error"
        406:
          description: "Niet aanvaardbaar, input ontbreekt"
        500:
          description: "Data verwerkingsfout, bijv onjuiste veldwaarde (string ipv integer)"

components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
      description: Eerst inloggen voordat API beschikbaar is
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    oper_factuur_in:
      type: object
      properties:
        ID:
          description: Database ID van het record
          type: integer
          format: int32
          example: 14
        JAAR:
          description: Jaar van de factuur
          type: integer
          format: int32
          example: 2014
        LID_ID:
          description: Lid ID voor de factuur. Verwijzing naar leden tabel
          type: integer
          example: 10321
        FACTUUR_NUMMER:
          description: Factuur nummer zoals dat door de boekhouding uitgedeeld is
          type: string
          example: "F00012"
        OMSCHRIJVING:
          description: Omschrijving van de factuurregel
          type: string
          example: "Contributie 2028"
        GEFACTUREERD:
          description: Contributie in euro voor deze factuur
          type: number
          example: 980.00


    oper_facturen:
      type: object
      allOf:
        - $ref: '#/components/schemas/oper_factuur_in'
        - type: object
          properties:
            LIDNR:
              description: Kopie van lidnr zoals dat in de leden tabel staat
              type: string
              example: "200912"
            NAAM:
              description: Naam van het lid
              type: string
              example: "Momfort de Mol"
            LIDTYPE_ID:
              description: Het soort lid (jeugdlid, lid, donateur). Verwijzing naar type tabel
              type: integer
              format: int32
              example: 603
            OPGEZEGD:
              description: Heeft het lid zijn/haar lidmaatschap opgezegd?
              type: boolean
              example: false
            LEEFTIJD:
              description: Leeftijd van het lid op 1 januari van het te factureren jaar
              type: integer
              format: int16
              example: 12
            VERWIJDERD:
              description: Is dit record gemarkeerd als verwijderd?
              type: boolean
              example: 0
            LAATSTE_AANPASSING:
              description: Tijdstempel van laaste aanpassing in de database
              type: string
              format: date-time
              example: "2021-05-05 20:13:59Z"

    view_facturen_dataset:
      type: object
      allOf:
        - $ref: '#/components/schemas/oper_facturen'

    view_facturen:
      type: object
      properties:
        totaal:
          description: Aantal records dat voldoet aan de criteria in de database
          type: integer
          format: int32
          example: 287
        laatste_aanpassing:
          description: Tijdstempel van laaste aanpassing in de database van de records dat voldoet aan de criteria
          type: string
          format: date-time
          example: "2019-01-05 10:09:53"
        hash:
          description: hash van de dataset
          type: string
          example: "dd00bff"
        dataset:
          description: De dataset met records
          type: array
          items:
            $ref: '#/components/schemas/view_facturen_dataset'
