openapi: 3.0.2
info:
  title: RefVliegtuigen
  description: Vliegtuig referentie data. Andere tabellen verwijzen naar deze tabel
  version: '1.0'
       
paths:
  /Vliegtuigen/CreateTable:
    post:
      security:
        - basicAuth: [] 
        - bearerAuth: []     
      summary: Creeer database objecten
      parameters:
        - in: query
          name: FILLDATA
          description: Dummy records aanmaken
          required: true
          schema:
            type: boolean
      responses:
        201:
          description: "Aangemaakt, Tabel toegevoegd"
        500:
          description: "Data verwerkingsfout, bijv omdat de tabel al bestaat" 

  /Vliegtuigen/CreateViews:
    post:
      security:
        - basicAuth: [] 
        - bearerAuth: []     
      summary: Creeer database views
      responses:
        201:
          description: "Aangemaakt, View toegevoegd"
        500:
          description: "Data verwerkingsfout, view niet aangemaak"    

  /Vliegtuigen/GetObject:
    get:
      security:
        - basicAuth: [] 
        - bearerAuth: []     
      summary: Haal een enkel vliegtuig op uit de database
      parameters:
        - in: query
          name: ID
          description: Database ID van het vliegtuig record
          required: true
          schema:
            type: integer
            format: int32
      responses:
        200:
          description: "OK, data succesvol opgehaald"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ref_vliegtuigen'
        404:
          description: "Data niet gevonden"
        405:
          description: "Methode niet toegestaan, input validatie error"  
        406:
          description: "Niet aanvaardbaar, input ontbreekt"    
        500:
          description: "Data verwerkingsfout, bijv onjuiste veldwaarde (string ipv integer)"      

  /Vliegtuigen/GetObjects:
    get:
      security:
        - basicAuth: [] 
        - bearerAuth: []     
      summary: Haal een lijst met vliegtuigen op uit de database. Query parameters worden in AND conditie gebruikt
      parameters:
        - in: query
          name: ID
          description: Database ID van het aanwezig record
          required: false
          schema:
            type: integer
            format: int32
            example: 10400    
        - in: query
          name: VERWIJDERD
          description: Toon welke records verwijderd zijn. Default = false
          required: false
          schema:
            type: boolean              
        - in: query
          name: LAATSTE_AANPASSING
          description: Laatste aanpassing op basis van records in dataset. Bedoeld om data verbruik te verminderen. Dataset is daarom leeg
          required: false
          schema:
            type: boolean
        - in: query
          name: HASH
          description: HASH van laatste GetObjects aanroep. Indien bij nieuwe aanroep dezelfde data bevat, dan volgt http status code 304. In geval dataset niet hetzelfde is, dan komt de nieuwe dataset terug. Ook bedoeld om dataverbruik te vermindereren. Er wordt alleen data verzonden als het nodig is.
          required: false
          schema:
            type: string                
        - in: query
          name: SORT
          description: Sortering van de velden in ORDER BY formaat. Default = CLUBKIST DESC, VOLGORDE, REGISTRATIE
          required: false
          schema:
            type: string     
        - in: query
          name: MAX
          description: Maximum aantal records in de dataset. Gebruikt in LIMIT query
          required: false
          schema:
            type: integer
            format: int32
            minimum: 1  
        - in: query
          name: START
          description: Eerste record in de dataset. Gebruikt in LIMIT query
          required: false
          schema:
            type: integer
            format: int32
            minimum: 1  
        - in: query        
          name: VELDEN
          description: Welke velden moet opgenomen worden in de dataset
          required: false
          schema:
            type: string                                    
        - in: query        
          name: SELECTIE
          description: Zoek in de REGISTRATIE, CALLSIGN, FLARM_CODE
          required: false
          schema:
            type: string
        - in: query
          name: IN
          description: Een of meerdere vliegtuig database IDs in CSV formaat. AND conditie als er geen andere parameters zijn, anders OR conditie
          required: false
          schema:
            type: string   
        - in: query
          name: TYPES
          description: Zoek op een of meerder type vliegtuig(en). Types als CSV formaat
          required: false
          schema:
            type: string                    
        - in: query
          name: ZITPLAATSEN
          description: Zoek op zitplaatsen 1/2
          required: false
          schema:
            type: integer
            format: int32                               
        - in: query
          name: CLUBKIST
          description: Haal alle clubvliegtuigen op
          required: false
          schema:
            type: boolean   
        - in: query
          name: ZELFSTART
          description: Haal alle zelfstarters op.
          required: false
          schema:
            type: boolean   
        - in: query
          name: SLEEPKIST
          description: Haal alle sleepkisten op.
          required: false
          schema:
            type: boolean           
        - in: query
          name: TMG
          description: Haal alle TMGs op.
          required: false
          schema:
            type: boolean                           
      responses:
        200:
          description: "OK, data succesvol opgehaald"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/view_vliegtuigen'
        304:
          description: "Data niet gemodificeerd, HASH in aanroep == hash in dataset"                     
        405:
          description: "Methode niet toegestaan, input validatie error"  
        500:
          description: "Data verwerkingsfout, bijv onjuiste veldwaarde (string ipv integer)"         

  /Vliegtuigen/DeleteObject:
    delete:
      security:
        - basicAuth: [] 
        - bearerAuth: []     
      summary: Markeer record als verwijderd.
      parameters:
        - in: query
          name: ID
          description: Database ID van het vliegtuig record. Meerdere ID's in CSV formaat
          required: true
          schema:
            type: string
        - in: query
          name: VERIFICATIE
          description: Controleer of record bestaat voordat het verwijderd wordt. Default = true
          required: false
          schema:
            type: boolean            
      responses:
        204:
          description: "Vliegtuig verwijderd"
        401:
          description: "Niet geautoriseerd, geen schrijfrechten"   
        404:
          description: "Data niet gevonden"             
        405:
          description: "Methode niet toegestaan, input validatie error"  
        406:
          description: "Niet aanvaardbaar, input ontbreekt"        
        500:
          description: "Data verwerkingsfout, bijv onjuiste veldwaarde (string ipv integer)" 

  /Vliegtuigen/RestoreObject:
    patch:
      security:
        - basicAuth: [] 
        - bearerAuth: []     
      summary: Record dat verwijderd is terug halen. VERWIJDERD marker kijrgt reset
      parameters:
        - in: query
          name: ID
          description: Database ID van het record. Meerdere ID's in CSV formaat
          required: true
          schema:
            type: string           
      responses:
        202:
          description: "Record(s) hersteld" 
        401:
          description: "Niet geautoriseerd, geen schrijfrechten"  
        404:
          description: "Data niet gevonden"        
        405:
          description: "Methode niet toegestaan, input validatie error"  
        406:
          description: "Niet aanvaardbaar, input ontbreekt"            
        500:
          description: "Data verwerkingsfout, bijv onjuiste veldwaarde (string ipv integer)" 

  /Vliegtuigen/SaveObject:
    post:
      security:
        - basicAuth: [] 
        - bearerAuth: []     
      summary: Voeg nieuw vliegtuig toe
      requestBody:
        description: Vliegtuig data
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ref_vliegtuigen_in'
      responses:
        200:
          description: "OK, data succesvol toegevoegd"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ref_vliegtuigen'  
        401:
          description: "Niet geautoriseerd, geen schrijfrechten"                    
        405:
          description: "Methode niet toegestaan, input validatie error"  
        406:
          description: "Niet aanvaardbaar, input ontbreekt"          
        409:
          description: "Conflict, registratie bestaat al"  
        500:
          description: "Data verwerkingsfout, bijv onjuiste veldwaarde (string ipv integer)"                   
    put:
      security:
        - basicAuth: [] 
        - bearerAuth: []     
      summary: Update bestaand vliegtuig
      requestBody:
        description: Vliegtuig data
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ref_vliegtuigen_in'
      responses:
        200:
          description: "OK, data succesvol aangepast"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ref_vliegtuigen'  
        401:
          description: "Niet geautoriseerd, geen schrijfrechten"  
        404:
          description: "Data niet gevonden"                    
        405:
          description: "Methode niet toegestaan, input validatie error"  
        406:
          description: "Niet aanvaardbaar, input ontbreekt"          
        409:
          description: "Conflict, registratie bestaat al"  
        500:
          description: "Data verwerkingsfout, bijv onjuiste veldwaarde (string ipv integer)" 

components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
      description: Eerst inloggen voordat API beschikbaar is
    bearerAuth:            
      type: http
      scheme: bearer
      bearerFormat: JWT         

  schemas:
    ref_vliegtuigen_in:
      type: object
      properties:
        ID:
          description: Database ID van het vliegtuig record
          type: integer
          format: int32
          example: 12871
        REGISTRATIE:
          description: Het registratie nummer van het vliegtuig
          type: string
          maxLength: 8
          example: "PH-1234"
        CALLSIGN:
          description: Optioneel het callsign van het vliegtuig
          type: string
          maxLength: 8
          example: AA
        FLARMCODE:
          description: De flarmcode zoals deze wordt uitgezonden. Zo kunnen we ontvangen flarm data herleiden naar een vliegtuig uit de database
          type: string
          maxLength: 6
          example: 123456
        ZITPLAATSEN:
          description: Het aantal zitplaatsen. Is 1 of 2. 
          type: integer
          format: int32
          example: 1
        ZELFSTART:
          description: Kan het vliegtuig op eigen kracht starten. 
          type: boolean
          example: 0
        CLUBKIST:
          description: Is het een club vliegtuig? 
          type: boolean
          example: 1
        TMG:
          description: Is het een TMG? 
          type: boolean
          example: 0
        SLEEPKIST:
          description: Is het een sleepvliegtuig? 
          type: boolean
          example: 0
        TYPE_ID:
          description: Link naar vliegtuig type tabel. Alleen nodig voor clubvliegtuigen
          type: integer
          format: int32   
          example: 12   
        VOLGORDE:
          description: Volgorde van vliegtuiglijst, bedoeld voor club vliegtuigen
          type: integer
          format: int32   
          example: 12
        INZETBAAR:
          description: Mag het vliegtuig vliegen?
          type: boolean
          example: 1
        URL:
          description: URL naar het handboek
          type: string
          example: 1  
        BEVOEGDHEID_LOKAAL_ID:
          description: Link naar comptentie om met deze kist lokaal te vliegen
          type: integer
          format: int32   
        BEVOEGDHEID_OVERLAND_ID:
          description: Link naar comptentie om met deze kist overland te vliegen
          type: integer
          format: int32             
        OPMERKINGEN:
          description: De opmerkingen die ingevoerd zijn
          type: string
          maxLength: 255
          example: Radio stoort bij snelheid boven 150 km/h   

    ref_vliegtuigen:
      type: object
      allOf:
      - $ref: '#/components/schemas/ref_vliegtuigen_in' 
      - type: object
        properties:
          VERWIJDERD:
            description: Is dit record gemarkeerd als verwijderd?  
            type: boolean
            example: 0            
          LAATSTE_AANPASSING:
            description: Tijdstempel van laaste aanpassing in de database
            type: string
            format: date-time 
            example: "2020-03-03 17:14:50Z" 

    view_vliegtuigen_dataset:
      type: object
      allOf:
        - $ref: '#/components/schemas/ref_vliegtuigen'
        - type: object
          properties:
            VLIEGTUIGTYPE: 
              description: Beschrijving van het vliegtuig type
              type: string
              example: Discus CS
            REG_CALL: 
              description: Vliegtuig registratie en callsign
              type: string
              example: PH-1076 (E2) 
            BEVOEGDHEID_LOKAAL: 
              description: Omschrijving van lokale bevoegdheid
              type: string
            BEVOEGDHEID_OVERLAND: 
              description: Omschrijving van overland bevoegdheid
              type: string
    view_vliegtuigen:
      type: object
      properties:
        totaal:
          description: Aantal records dat voldoet aan de criteria in de database
          type: integer
          format: int32
          example: 287
        laatste_aanpassing:
          description: Tijdstempel van laaste aanpassing in de database van de records dat voldoet aan de criteria
          type: string
          format: date-time 
          example: "2020-02-12 21:15:16" 
        hash: 
          description: hash van de dataset
          type: string
          example: "400000f"            
        dataset:
          description: De dataset met records
          type: array
          items: 
            $ref: '#/components/schemas/view_vliegtuigen_dataset'
