version: '3.7'

services:
  helios:
    image: 301167/php-apache-pdo
    container_name: helios
    ports:
      - 8082:80
    volumes:
      - ..:/var/www/html
    networks:
      - proxy
      - mariadb-vnet
    restart: always
  mariadb:
    image: mariadb
    container_name: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: rootroot
      TZ: Europe/Amsterdam

    volumes:
      - db_data:/var/lib/mysql
    networks:
      - mariadb-vnet
    ports:
      - 3306:3306
    restart: always
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mariadb
      UPLOAD_LIMIT: 500M

    ports:
      - 8081:80
    networks:
      - proxy
      - mariadb-vnet
    restart: always

networks:
  proxy:
  mariadb-vnet:
    name: mariadb-vnet
    driver: bridge

volumes:
  db_data:
    driver: local

